# Generated by Django 4.0.2 on 2022-04-13 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_usercashwithdrawal_peycode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercashwithdrawal',
            old_name='peycode',
            new_name='paycode',
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 13, 15, 41, 56, 932199), verbose_name='زمان انقضا'),
        ),
    ]
