# Generated by Django 4.0.2 on 2022-04-27 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_verificationcode_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 27, 15, 50, 17, 376617), verbose_name='زمان انقضا'),
        ),
    ]
