# Generated by Django 4.0.2 on 2022-05-13 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_verificationcode_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 13, 11, 54, 18, 179864), verbose_name='زمان انقضا'),
        ),
    ]
