# Generated by Django 4.0.4 on 2022-06-21 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_user_date_of_birth_user_father_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_card',
            field=models.ImageField(blank=True, null=True, upload_to='id_card'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 21, 16, 13, 43, 529108), verbose_name='زمان انقضا'),
        ),
    ]
