# Generated by Django 4.0.4 on 2022-06-22 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_user_id_card_alter_verificationcode_expire_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face',
            field=models.ImageField(blank=True, null=True, upload_to='id_card'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_full_authentication',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 22, 16, 17, 54, 300321), verbose_name='زمان انقضا'),
        ),
    ]
