# Generated by Django 4.0.4 on 2022-06-25 07:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_verificationcode_expire_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserKucoinAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('futures_api_key', models.CharField(max_length=1000)),
                ('futures_secret', models.CharField(max_length=1000)),
                ('futures_passphrase', models.CharField(max_length=1000)),
                ('spot_api_key', models.CharField(max_length=1000)),
                ('spot_secret', models.CharField(max_length=1000)),
                ('spot_passphrase', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 25, 12, 13, 39, 167515), verbose_name='زمان انقضا'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_kucoin_api',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.userkucoinapi'),
        ),
    ]
