# Generated by Django 4.0.4 on 2022-06-25 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_user_user_kucoin_api_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 25, 16, 14, 11, 447798), verbose_name='زمان انقضا'),
        ),
    ]
