# Generated by Django 4.0.4 on 2022-06-25 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_alter_verificationcode_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 25, 16, 14, 16, 597486), verbose_name='زمان انقضا'),
        ),
    ]
