# Generated by Django 4.0.4 on 2022-06-26 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_alter_verificationcode_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 26, 12, 11, 59, 138648), verbose_name='زمان انقضا'),
        ),
    ]
