# Generated by Django 4.0.4 on 2022-06-26 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_alter_verificationcode_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercashwithdrawal',
            name='bank_card_number',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 26, 17, 37, 7, 646698), verbose_name='زمان انقضا'),
        ),
    ]
