# Generated by Django 4.0.4 on 2022-07-02 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_alter_usercashwithdrawal_bank_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 12, 47, 58, 957774), verbose_name='زمان انقضا'),
        ),
    ]
