# Generated by Django 4.0.4 on 2022-07-02 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_alter_verificationcode_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 15, 17, 35, 36063), verbose_name='زمان انقضا'),
        ),
    ]
