# Generated by Django 4.0.4 on 2022-07-29 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_alter_verificationcode_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 29, 12, 22, 57, 594322), verbose_name='زمان انقضا'),
        ),
    ]
