# Generated by Django 4.0.4 on 2022-08-01 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_alter_verificationcode_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 1, 15, 14, 16, 130612), verbose_name='زمان انقضا'),
        ),
    ]
