# Generated by Django 4.0.4 on 2022-09-05 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_alter_verificationcode_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 5, 12, 37, 31, 262482), verbose_name='زمان انقضا'),
        ),
    ]
