# Generated by Django 4.0.4 on 2022-09-06 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_alter_verificationcode_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 6, 19, 51, 4, 379437), verbose_name='زمان انقضا'),
        ),
    ]
