# Generated by Django 4.0.4 on 2022-09-09 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_alter_verificationcode_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 9, 14, 4, 33, 129499), verbose_name='زمان انقضا'),
        ),
    ]
