# Generated by Django 4.0.4 on 2022-09-10 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_alter_verificationcode_expire_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='user-images'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 12, 53, 1, 693074), verbose_name='زمان انقضا'),
        ),
    ]
