# Generated by Django 4.0.4 on 2022-09-16 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_user_user_image_alter_verificationcode_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 16, 13, 47, 53, 759186), verbose_name='زمان انقضا'),
        ),
    ]
