# Generated by Django 4.0.4 on 2022-09-16 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_alter_verificationcode_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 16, 19, 38, 7, 715860), verbose_name='زمان انقضا'),
        ),
    ]
