# Generated by Django 4.0.4 on 2022-09-20 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0042_alter_verificationcode_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 20, 13, 44, 48, 964273), verbose_name='زمان انقضا'),
        ),
    ]
