# Generated by Django 4.0.2 on 2022-04-13 11:08

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=3000)),
                ('short_description', models.CharField(max_length=5000)),
                ('description', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to=news.models.new_upload_img_path)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
