# Generated by Django 4.0.4 on 2022-09-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='categories',
            field=models.ManyToManyField(to='news.category'),
        ),
    ]
