# Generated by Django 4.0.2 on 2022-04-13 11:08

import base_model.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('special_account_item', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('validity_date', models.DateTimeField()),
                ('percentage', base_model.models.IntegerRangeField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('count', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_private', models.BooleanField(default=False)),
                ('use_by', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(choices=[('online', 'آنلاین'), ('offline', 'کارت به کارت')], max_length=20)),
                ('amount', models.FloatField()),
                ('date_of_approval', models.DateTimeField(blank=True, null=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True)),
                ('validity_rate', models.IntegerField()),
                ('transaction_status', models.CharField(blank=True, max_length=300, null=True)),
                ('is_confirmation', models.BooleanField(default=False)),
                ('consultant_name', models.CharField(blank=True, max_length=300, null=True)),
                ('payment_receipt', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('is_send_receipt', models.BooleanField(default=False)),
                ('discount_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.discountcode')),
                ('special_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='special_account_item.specialaccountitem')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
