# Generated by Django 4.0.2 on 2022-04-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='last_updated_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
