# Generated by Django 4.0.4 on 2022-09-09 09:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_alter_story_visitors'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 9, 33, 39, 78171, tzinfo=utc)),
        ),
    ]
