# Generated by Django 4.0.4 on 2022-09-16 09:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftalarm',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 17, 9, 21, 1, 568517, tzinfo=utc)),
        ),
    ]
