# Generated by Django 4.0.4 on 2022-09-16 15:07

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0002_nftalarm_expire_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftalarm',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nftalarm',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 17, 15, 7, 8, 25887, tzinfo=utc)),
        ),
    ]
