# Generated by Django 4.0.4 on 2022-09-20 09:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0004_alter_nftalarm_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nftalarm',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 21, 9, 1, 34, 493043, tzinfo=utc)),
        ),
    ]
