# Generated by Django 4.0.4 on 2022-06-23 11:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trader_name', models.CharField(max_length=300)),
                ('trader_api_features', models.CharField(max_length=1000)),
                ('trader_api_spot', models.CharField(max_length=1000)),
                ('initial_balance', models.FloatField()),
                ('win_rate', models.PositiveIntegerField()),
                ('exchange', models.CharField(default='کوکوین', max_length=200)),
                ('basket_risk', models.CharField(max_length=200)),
                ('maximum_loss', models.PositiveIntegerField()),
                ('maximum_profit', models.PositiveIntegerField()),
                ('estimated_time', models.PositiveIntegerField()),
                ('time_of_start', models.DateTimeField()),
                ('settlement_percentage', models.PositiveIntegerField()),
                ('blocked_users', models.ManyToManyField(related_name='blocked_users', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='participants', to=settings.AUTH_USER_MODEL)),
                ('stages', models.ManyToManyField(to='copy_trade.stage')),
            ],
        ),
    ]
