# Generated by Django 4.0.4 on 2022-06-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copy_trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='is_freeze',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basket',
            name='orders_type',
            field=models.CharField(blank=True, choices=[('f', 'futures'), ('s', 'spot')], max_length=10, null=True),
        ),
    ]
