# Generated by Django 4.0.4 on 2022-06-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copy_trade', '0004_basket_is_accept_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
