# Generated by Django 4.0.4 on 2022-06-25 15:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('copy_trade', '0005_basket_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='orders_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='is_pay_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stage',
            name='pay_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='payers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
