# Generated by Django 4.0.4 on 2022-06-25 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('copy_trade', '0006_basket_orders_count_stage_is_pay_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='trader_api_features',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='trader_api_spot',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='trader_name',
        ),
        migrations.AddField(
            model_name='basket',
            name='trader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
