# Generated by Django 4.0.4 on 2022-07-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copy_trade', '0007_remove_basket_trader_api_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='trader_futures_api',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='trader_futures_passphrase',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='trader_futures_secret',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='trader_spot_api',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='trader_spot_passphrase',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='trader_spot_secret',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
