# Generated by Django 4.0.4 on 2022-07-09 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('copy_trade', '0009_remove_basket_time_of_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('side', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('stopPrice', models.CharField(blank=True, max_length=100, null=True)),
                ('stopPriceType', models.CharField(blank=True, max_length=100, null=True)),
                ('leverage', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='basket',
            name='orders_count',
        ),
        migrations.AlterField(
            model_name='basket',
            name='basket_risk',
            field=models.CharField(max_length=200, verbose_name='ریسک سبد'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='estimated_time',
            field=models.PositiveIntegerField(verbose_name='زمان تخمینی'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='exchange',
            field=models.CharField(default='کوکوین', max_length=200, verbose_name='صرافی'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='initial_balance',
            field=models.FloatField(verbose_name='موجودی اولیه'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='maximum_loss',
            field=models.PositiveIntegerField(verbose_name='حداکثر ضرر'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='maximum_profit',
            field=models.PositiveIntegerField(verbose_name='حداکثر سود'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='orders_type',
            field=models.CharField(blank=True, choices=[('f', 'futures'), ('s', 'spot')], max_length=10, null=True, verbose_name='نوع سبد'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='settlement_percentage',
            field=models.PositiveIntegerField(verbose_name='درصد تسویه'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='stages',
            field=models.ManyToManyField(blank=True, to='copy_trade.stage', verbose_name='stages'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='trader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='تریدر'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='trader_futures_api',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='futures api key تریدر'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='trader_futures_passphrase',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='futures passphrase تریدر'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='trader_futures_secret',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='futures secret key تریدر'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='trader_spot_api',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='spot api key تریدر'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='trader_spot_passphrase',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='spot passphrase تریدر'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='trader_spot_secret',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='spot secret key تریدر'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='win_rate',
            field=models.PositiveIntegerField(verbose_name='win rate'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='amount',
            field=models.PositiveBigIntegerField(verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='is_pay_time',
            field=models.BooleanField(default=False, verbose_name='زمان پرداخت باشد'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='pay_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='payers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='پرداخت کنندگان'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='basket',
            name='orders',
            field=models.ManyToManyField(to='copy_trade.order'),
        ),
    ]
