# Generated by Django 4.0.2 on 2022-04-13 11:08

import base_model.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignalNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('amount', models.FloatField()),
                ('is_touched', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpotSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('coin_symbol', models.CharField(max_length=30)),
                ('proposed_capital', base_model.models.IntegerRangeField()),
                ('r_and_r', models.FloatField()),
                ('type_of_investment', models.CharField(choices=[['بلند مدت', 'بلند مدت'], ['کوتاه مدت', 'کوتاه مدت']], max_length=30)),
                ('profit_of_signal_amount', models.FloatField(blank=True, null=True)),
                ('stop_loss', models.FloatField()),
                ('entry', models.FloatField()),
                ('is_touched_entry', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=250, null=True)),
                ('signal_news', models.ManyToManyField(blank=True, null=True, to='signals.SignalNews')),
                ('targets', models.ManyToManyField(to='signals.Target')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FuturesSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('coin_symbol', models.CharField(max_length=30)),
                ('amount', base_model.models.IntegerRangeField()),
                ('leverage', models.IntegerField()),
                ('type_of_investment', models.CharField(choices=[['SHORT', 'SHORT'], ['LONG', 'LONG']], max_length=30)),
                ('profit_of_signal_amount', models.FloatField(blank=True, null=True)),
                ('stop_loss', models.FloatField()),
                ('entry', models.FloatField()),
                ('is_touched_entry', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=250, null=True)),
                ('signal_news', models.ManyToManyField(blank=True, null=True, to='signals.SignalNews')),
                ('targets', models.ManyToManyField(to='signals.Target')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
