# Generated by Django 4.0.2 on 2022-05-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0002_signalalarm_futuressignal_alarms_spotsignal_alarms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futuressignal',
            name='alarms',
            field=models.ManyToManyField(blank=True, to='signals.SignalAlarm'),
        ),
        migrations.AlterField(
            model_name='spotsignal',
            name='alarms',
            field=models.ManyToManyField(blank=True, to='signals.SignalAlarm'),
        ),
    ]
