# Generated by Django 4.0.2 on 2022-05-13 07:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signals', '0003_alter_futuressignal_alarms_alter_spotsignal_alarms'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalnews',
            name='seen_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
